services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: devcontainer-tailscale
    hostname: claude-code-dev
    env_file:
      - .env
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: '${TZ:-America/Los_Angeles}'
    container_name: claude-code-devcontainer
    network_mode: service:tailscale
    env_file:
      - .env
    depends_on:
      - tailscale
    volumes:
      - ..:/workspace:cached
      - claude-code-bashhistory:/commandhistory
      - ${HOME}/.claude:/home/node/.claude
      - ${HOME}/.gitconfig:/home/node/.gitconfig-host:ro
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - CLAUDE_CONFIG_DIR=/home/node/.claude
      - POWERLEVEL9K_DISABLE_GITSTATUS=true
    working_dir: /workspace
    command: sleep infinity
    user: node

volumes:
  tailscale-state:
    driver: local
  claude-code-bashhistory:
    driver: local
